### ISSUE TITLE
While toggling theme from (i.e dark to light) tool-tip doesn't change.

### ISSUE THREAD

**Issue by Usamaahmad751** [9inpachi/krit#2] opened 2020-07-17 12:41 UTC
Hey! 9inpachi Really appreciate your efforts in creating a charming portfolio. But I noticed a bug while toggling the theme (i.e from dark to light) the tooltip doesn't change. It seems you made it somewhere static or the condition is not working properly. Please have a look at it. If you want me to resolve this issue. I would love in contributing into this repository again. Thanks.

**Comment by 9inpachi** [comment] 2020-07-17 12:58
Thanks for pointing this out @Usamaahmad751 !

That is intended behavior. If you see in the official [material docs for Tooltips](https://material-ui.com/components/tooltips/) you will see that the tooltip theme will remain the same even after changing the theme from top right. That's because the tooltip is valid in contrast for both light and dark modes.

But if you want to customize it for `krit`'s theme, then feel free to contribute! It will be much appreciated!

**Comment by Usamaahmad751** [comment] 2020-07-17 13:38
Yeah, I see. Would be great if we replace `dark` with `light/dark`. I think it will make more sense.

**Comment by 9inpachi** [comment] 2020-07-17 14:15
Sure does. Feel free to send a PR.

Note that material styles are to be updated globally so anything you do to change the material icons color or background you should do it in the main css file -> [index.scss](https://github.com/9inpachi/krit/blob/master/src/index.scss).

**Comment by Usamaahmad751** [comment] 2020-07-20 05:26
Hey Fawad! Thanks for reviewing my pull request. As this issue is fixed you can mark it close with reference to the commit. Thanks for bearing with me. Have a nice day!

**Comment by 9inpachi** [comment] 2020-07-20 12:24
@Usamaahmad751 Yes sure.

For future references, you can mention "Closes #<issue_number>" or "Fixes #<issue_number>" at the top of a pull request description for automatically closing the issue when a PR is accepted.

**Closed as completed by 9inpachi** 2020-07-20 12:24 UTC
